### ISSUE TITLE
CRC failed when unflatting poppy-torso-xu4-2016-05-25.img.zip

### ISSUE THREAD

**Issue by lcotonea** [poppy-project/poppy-torso#25]
Hi,

When I try to extract img from the file "poppy-torso-xu4-2016-05-25.img.zip", I have a CRC error (7zip). Is it normal?

Regards

**Comment by show0k** [comment]
I downloaded [poppy-torso-xu4-2016-05-25.img.zip](https://github.com/poppy-project/poppy-torso/releases/download/1.0.2gm/poppy-torso-xu4-2016-05-25.img.zip) and have no issue to unzip it. I am not using 7zip but I think that it is more probably an issue of your download.

To verify if we have the same file:
MD5 (poppy-torso-xu4-2016-05-25.img.zip) = 00da36dd8ec7a7f9f00aa544dc1ded08
MD5 (poppy-torso-xu4-2016-05-25.img) = afa1fc3d80a0dde88a0f5aeff3afd52f

**Comment by lcotonea** [comment]
7zip, or archive manager (debian distro), and probably GUI archive manager doesn't seem  to unfalte correctly the image file. Maybe because of its size.
Whatever, with the unzip linux command, the job has been done.
Many thanks!
