### ISSUE TITLE
Timeout exception while connecting to the robot in V-REP

### ISSUE THREAD

**Issue by fgolemo** [poppy-project/poppy-torso#27]
Hey guys,

when I want to run the Poppy Torso in V-REP and control it through a Jupyter Notebook, I follow your instructions on the poppy website and **everything is okay on Linux**.

But when I try to do the same **on Windows, I get a timeout exception in Jupyter**:
https://www.dropbox.com/s/4kyhtvppfjf65hh/Screenshot_20170210_190409.png?dl=0

The weird thing: **Snap works on Windows, only Jupyter does not**. I can click the link in the terminal and open Snap in my browser and control the robot from there, but the Jupyter Notebook for some reason doesn't let me connect.

Do you have any ideas how to resolve this? Any help appreciated.

Thanks,
Flo

* Windows 10

**Comment by show0k** [comment]
I have no Windows 10 laptop with me. Can you try to do the same thing with the Python interpreter instead of Jupyter notebook, and look if the issue is the same ? 

P.S. You can attach pictures to GitHub issues with a drag and drop.

**Comment by fgolemo** [comment]
Yes, same problem when using Python on the terminal.

Other things I tried:

- starting poppy-services as administrator
- running the Python client as administrator
- running V-Rep as administrator

I have a Windows laptop - I can show you the error on Monday.

**Comment by fgolemo** [comment]
Found the issue(s):

- For some reason my TeamViewer was blocking port 19999. I don't know why, because it's not an official port.
- The poppy-services script was blocking V-Rep. Again, no idea why. On Linux it is running fine, but on Windows I have to stop poppy-services, and then I can connect to the simulation in Python. You should add this to your documentation: If on Windows, stop poppy-services (or make sure they aren't running) before attempting to connect to your PoppyTorso in V-Rep using Python/Jupyter.

**Comment by show0k** [comment]
I don't even know of it could work on Linux. Only one instance of a robot can communicate to V-REP at a time.
You can start the HTTP API (to control the robot from Snap as you do with `poppy-services`) directly from Python (in the Jupyter notebook for example).
```python
from poppy.creatures import PoppyTorso
poppy = PoppyTorso(use_http=True, simulator='vrep')

```
