### ISSUE TITLE
Bust motors are not displayed in V-REP

### ISSUE THREAD

**Issue by show0k** [poppy-project/poppy-torso#6]
It's not a big issue, but poppy-torso seems to not have bust motors in V-REP scene:
![torso](https://cloud.githubusercontent.com/assets/3891499/8148975/94c741fa-12b4-11e5-9c11-3a15198f6109.png)
This issue is not present for poppy-humanoid:
![humanoid](https://cloud.githubusercontent.com/assets/3891499/8149012/c1c76c9c-12b5-11e5-9243-2529636d96d4.png)

**Comment by jjehl** [comment]
Bug fix with the new V-REP scene (branch dev)

**Comment by jjehl** [comment]
Fixed with the updated V-REP model.
